name: leaders_book
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 4.2.5

environment:
  sdk: ">=2.9.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.1.1
  firebase_analytics: ^10.0.4
  firebase_auth: ^4.1.1
  cloud_firestore: ^4.0.4
  cloud_functions: ^4.0.3
  url_launcher: ^6.1.6
  google_sign_in: ^5.4.2
  intl: ^0.17.0
  permission_handler: ^10.2.0
  path_provider: ^2.0.11
  in_app_purchase: ^3.0.8
  google_mobile_ads: ^2.2.0
  shared_preferences: ^2.0.15
  package_info_plus: ^1.4.2
  file_picker: ^4.6.1
  launch_review: ^3.0.1
  pdf: ^3.8.4
  flutter_local_notifications: ^12.0.1+1
  local_auth: ^2.1.2
  sign_in_with_apple: ^4.2.0
  provider: ^6.0.4
  universal_html: ^2.0.8
  crypto: ^3.0.2
  maps_launcher: ^2.0.1
  open_file: ^3.2.1
  firebase_app_check: ^0.1.1+3
  excel: ^2.0.0-null-safety-3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon-512.png"

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icon-512.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
