name: leaders_book
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 4.3.1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.5.3
  cloud_functions: ^4.1.1
  collection: ^1.15.0-nullsafety.4
  crypto: ^3.0.2
  excel: ^2.1.0
  file_picker: ^5.2.11
  firebase_analytics: ^10.2.1
  firebase_app_check: ^0.1.2+3
  firebase_auth: ^4.4.2
  firebase_core: ^2.10.0
  firebase_crashlytics: ^3.1.2
  flutter_riverpod: ^2.3.6
  fluttertoast: ^8.2.1
  google_mobile_ads: ^3.0.0
  google_sign_in: ^6.0.2
  in_app_purchase: ^3.1.5
  intl: ^0.17.0
  launch_review: ^3.0.1
  local_auth: ^2.1.6
  open_file: ^3.3.1
  package_info_plus: ^3.1.2
  path_provider: ^2.0.14
  pdf: ^3.10.1
  permission_handler: ^10.2.0
  pull_down_button: ^0.8.3
  rate_my_app: ^1.1.3
  shared_preferences: ^2.1.0
  sign_in_with_apple: ^4.3.0
  universal_html: ^2.2.1
  url_launcher: ^6.1.10

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon-512.png"

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icon-512.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
