name: leaders_book
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 4.3.9

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.8.4
  cloud_functions: ^4.4.0
  collection: ^1.17.1
  crypto: ^3.0.3
  cupertino_icons: ^1.0.4
  excel: ^2.1.0
  file_picker: ^5.3.3
  firebase_analytics: ^10.4.5
  firebase_app_check: ^0.1.5+2
  firebase_auth: ^4.7.3
  firebase_core: ^2.15.1
  firebase_crashlytics: ^3.3.5
  firebase_messaging: ^14.6.6
  flutter_local_notifications: ^15.1.0+1
  flutter_riverpod: ^2.3.7
  flutter_timezone: ^1.0.7
  fluttertoast: ^8.2.2
  google_mobile_ads: ^3.0.0
  google_sign_in: ^6.1.4
  http: ^1.1.0
  in_app_purchase: ^3.1.8
  intl: ^0.18.1
  launch_review: ^3.0.1
  local_auth: ^2.1.6
  open_file_plus: ^3.4.1
  package_info_plus: ^4.0.0
  path_provider: ^2.1.0
  pdf: ^3.10.4
  permission_handler: ^10.4.3
  pull_down_button: ^0.9.3
  rate_my_app: ^2.0.0
  shared_preferences: ^2.2.0
  sign_in_with_apple: ^5.0.0
  timezone: ^0.9.2
  universal_html: ^2.2.3
  url_launcher: ^6.1.12

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon-512.png"

dev_dependencies:
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icon-512.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
