allprojects {
    repositories {
        mavenCentral()
        google()
    }
}

rootProject.buildDir = '../build'
subprojects {
    afterEvaluate { project ->
        if (project.hasProperty('android')) {
            project.android {
                if (!hasProperty('namespace') || namespace == null || namespace.isEmpty()) {
                    // Assign a default namespace based on the project name or group
                    namespace = project.group.toString() ?: "com.example.${project.name}"
                }
            }
        }
    }
}
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
